DROP SEQUENCE BOARDSEQ;
DROP TABLE BOARD CASCADE CONSTRAINTS;

CREATE SEQUENCE BOARDSEQ;

CREATE TABLE BOARD (
	BOARDNO	NUMBER PRIMARY KEY,
	ID	VARCHAR2(200) NOT NULL,
	TITLE	VARCHAR2(500) NOT NULL,
	LIKENUM	NUMBER,
	REGDATE DATE NOT NULL,
	VIEWCOUNT	NUMBER ,
	FILENAME	VARCHAR2(500),
	CONTENT	VARCHAR2(1000)
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_USERBOARD_TO_BOARD_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USERBOARD" (
	"ID"
);

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id1','테스트제목1',1,SYSDATE,5,'테스트파일1','테스트내용입니다1');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id2','테스트제목2',1,SYSDATE,5,'테스트파일2','테스트내용입니다2');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id3','테스트제목3',1,SYSDATE,5,'테스트파일3','테스트내용입니다3');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id4','테스트제목4',1,SYSDATE,5,'테스트파일4','테스트내용입니다4');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id5','테스트제목5',1,SYSDATE,5,'테스트파일5','테스트내용입니다5');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id6','테스트제목6',1,SYSDATE,5,'테스트파일6','테스트내용입니다6');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id7','테스트제목7',1,SYSDATE,5,'테스트파일7','테스트내용입니다7');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id8','테스트제목8',1,SYSDATE,5,'테스트파일8','테스트내용입니다8');

INSERT INTO BOARD
VALUES(BOARDSEQ.NEXTVAL,'테스트id9','테스트제목9',1,SYSDATE,5,'테스트파일9','테스트내용입니다9');



SELECT * FROM BOARD;

SELECT BOARDNO,ID,TITLE,LIKENUM,REGDATE,VIEWCOUNT,FILENAME,CONTENT
FROM BOARD
ORDER BY BOARDNO DESC;

SELECT COUNT(*) FROM BOARD;

--1234

SELECT BOARDNO,ID,TITLE,LIKENUM,REGDATE,VIEWCOUNT,FILENAME,CONTENT
FROM(
	SELECT A.*,ROW_NUMBER() OVER(ORDER BY BOARDNO DESC) AS RNUM
	FROM BOARD A
)
WHERE RNUM BETWEEN 1 AND 4;


-- 5678

SELECT BOARDNO,ID,TITLE,LIKENUM,REGDATE,VIEWCOUNT,FILENAME,CONTENT
FROM(
	SELECT A.*,ROW_NUMBER() OVER(ORDER BY BOARDNO DESC) AS RNUM
	FROM BOARD A
)
WHERE RNUM BETWEEN 5 AND 8;


SELECT *
		FROM (SELECT A.*,ROW_NUMBER() OVER(ORDER BY BOARDNO DESC) AS RNUM FROM BOARD A)
		WHERE RNUM BETWEEN 1 AND 4;


SELECT BOARDNO,ID,TITLE,(SELECT COUNT(*) FROM USERLIKE WHERE BOARDNO = 2) AS LIKENUM,REGDATE,VIEWCOUNT,FILENAME,CONTENT
FROM BOARD
WHERE BOARDNO = 2;







