DROP TABLE "USERLIKE";

CREATE TABLE "USERLIKE" (
	"ID"	VARCHAR2(255)	NOT NULL,
	"BOARDNO"	NUMBER		NOT NULL,
	"LIKEYN"	VARCHAR2(2)		NULL
	CONSTRAINT USERLIKE_LIKEYN_CHK CHECK(LIKEYN IN ('Y','N'))
);

CREATE TABLE "USERLIKE" (
	"ID"	VARCHAR2(255)	NOT NULL,
	"BOARDNO"	NUMBER		NOT NULL
);

ALTER TABLE "USERLIKE" ADD CONSTRAINT "PK_USERLIKE" PRIMARY KEY (
	"ID",
	"BOARDNO"
);

ALTER TABLE "USERLIKE" ADD CONSTRAINT "FK_USER_TO_USERLIKE_1" FOREIGN KEY (
	"ID"
)
REFERENCES "USERBOARD" (
	"ID"
);

ALTER TABLE "USERLIKE" ADD CONSTRAINT "FK_BOARD_TO_USERLIKE_1" FOREIGN KEY (
	"BOARDNO"
)
REFERENCES "BOARD" (
	"BOARDNO"
);

INSERT INTO USERLIKE VALUES('dd',1,'Y');
INSERT INTO USERLIKE VALUES('dd',2,'N');
INSERT INTO USERLIKE VALUES('rlawlsdn',1,'Y');
INSERT INTO USERLIKE VALUES('rlawlsdn',2,'Y');

SELECT * FROM USERLIKE;

SELECT LIKEYN FROM USERLIKE WHERE boardno = 1 AND id = 'dd';


INSERT INTO USERLIKE VALUES('dd',1);
INSERT INTO USERLIKE VALUES('dd',2);
INSERT INTO USERLIKE VALUES('rlawlsdn',1);

SELECT ID FROM USERLIKE WHERE BOARDNO = 1;
SELECT COUNT(*) FROM USERLIKE WHERE BOARDNO = 1 AND ID = 'rlawlsdn';