

DROP TABLE USERBOARD CASCADE CONSTRAINT;


CREATE TABLE "USERBOARD" (
	"ID"	VARCHAR2(255) PRIMARY KEY,
	"NAME"	VARCHAR2(255) NOT NULL,
	"PW"	VARCHAR2(255) ,
	"ADDR"	VARCHAR2(255) ,
	"PHONE"	VARCHAR2(255) ,
	"EMAIL"	VARCHAR2(255) ,
	"GRADE"	VARCHAR2(255) NOT NULL,
	"YN"	VARCHAR2(2) NOT NULL,
	"PENCOUNT"	NUMBER NOT NULL,
	"CONFIRM" VARCHAR2(2) ,
	"SNS" VARCHAR2(255),
	"IMAGE" VARCHAR2(255) NULL
);

INSERT INTO "USERBOARD"
VALUES('rlawlsdn','김진우','rlawlsdn','주소','01066727677','propose_7677@naver.com','admin','N',0,'N','origin','');

UPDATE USERBOARD SET GRADE='admin' WHERE ID='admin';

SELECT * FROM "USERBOARD";
COMMIT;